apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongo.baseName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mongo.label }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.mongo.label }}
    spec:
      containers:
        - image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag | default .Chart.AppVersion }}"
          name: {{ .Chart.Name }}-{{ .Values.mongo.baseName }}
          ports:
            - containerPort: {{ .Values.mongo.service.port }}
          imagePullPolicy: {{ .Values.mongo.pullPolicy }}
          volumeMounts:
            - mountPath: /data/db
              name: general-disk
              subPath: mongodb/data
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongo.username }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongo.password }}
          resources:
            limits:
              memory: "520Mi"
              cpu: "0.3"
            requests:
              cpu: "0"
              memory: "0"
      volumes:
        - name: general-disk
          persistentVolumeClaim:
            claimName: general-disk
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.service.name }}
  labels:
    app: {{ .Values.mongo.label }}
spec:
  ports:
    - port: 27017
  type: {{ .Values.mongo.service.type }}
  selector:
    app: {{ .Values.mongo.label }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: general-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
