apiVersion: v1
kind: Secret
metadata:
  name: tls-ca
  namespace: vault
type: kubernetes.io/tls
data: 
  tls.crt: >-
    {{ .Files.Get "tls/ca.pem" | b64enc }}
  tls.key: >-
    {{ .Files.Get "tls/ca-key.pem" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-server
  namespace: vault
type: kubernetes.io/tls
data: 
  tls.crt: >-
    {{ .Files.Get "tls/vault.pem" | b64enc }}
  tls.key: >-
    {{ .Files.Get "tls/vault-key.pem" | b64enc }}
