apiVersion: apps/v1
kind: Deployment
metadata:
  name: manual-rp-deployment
  labels:
    app: node
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
     app: node
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-pre-populate-only: 'true'
        vault.hashicorp.com/agent-inject-secret-helloworld: "secret/basic-secret/helloworld"
        vault.hashicorp.com/agent-inject-template-helloworld: |
          {{`{{ with secret "secret/basic-secret/helloworld" -}}
            export apiKey="{{ .Data.apiKey }}"
          {{- end }}`}}
        vault.hashicorp.com/role: "basic-secret-role"
      labels:
        app: node
    spec:
      serviceAccountName: basic-secret
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["/bin/sh"]
          args:
            ['-c', 'source /vault/secrets/helloworld && npm start']
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: DYNAMIC_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: manual-rp-configmap
                  key: DYNAMIC_IMAGE
