apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  labels:
    app: {{ .Values.app.label }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.app.label }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.baseName }}
  labels:
    app: {{ .Values.app.label }}
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.autoscaling.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.app.label }}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/role: {{ .Values.k8sAuth.role.name }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/tls-skip-verify: "true"

        vault.hashicorp.com/agent-inject-secret-{{ .Values.mongo.secret.name }}: {{ .Values.mongo.secret.path }}
        vault.hashicorp.com/agent-inject-template-{{ .Values.mongo.secret.name }}: |
          {{ "{{" }} with secret "{{ .Values.mongo.secret.path }}" -{{ "}}" }}
            export dbUrl="mongodb://{{ "{{" }} .Data.username {{ "}}" }}:{{ "{{" }} .Data.password {{ "}}" }}@{{ .Values.mongo.service.name }}:27017"
          {{ "{{" }}- end {{ "}}" }}

        vault.hashicorp.com/agent-inject-secret-{{ .Values.app.secret.name }}: {{ .Values.app.secret.path }}
        vault.hashicorp.com/agent-inject-template-{{ .Values.app.secret.name }}: |
          {{ "{{" }} with secret "{{ .Values.app.secret.path }}" -{{ "}}" }}
            export apiKey="{{ "{{" }} .Data.apiKey {{ "}}" }}"
          {{ "{{" }}- end {{ "}}" }}
      labels:
        app: {{ .Values.app.label }}
    spec:
      serviceAccountName: {{ .Values.k8sAuth.role.serviceAccountNames }}
      containers:
        - name: {{ .Chart.Name }}-{{ .Values.app.baseName }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          command: ["/bin/sh"]
          args:
            ['-c', 'source /vault/secrets/{{ .Values.app.secret.name }} && source /vault/secrets/{{ .Values.mongo.secret.name }} && npm run start:fnw']
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.service.port }}
              protocol: TCP
          env:
            - name: DYNAMIC_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.configMap.name }}
                  key: DYNAMIC_IMAGE