apiVersion: v1
kind: Service
metadata:
  name: manual-rp-service
  labels:
    app: node
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: node
