replicaCount: 1

app:
  image:
    repository: leosimonetti/sne-rp1
    pullPolicy: Always
    tag: "latest"

  label: "node"

  service:
    type: LoadBalancer
    port: 3000

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

mongo:
  service:
    name: mongo-srv