name: Live cluster security scans

on:
  push:
    branches:
    - main

jobs:
  cluster:
    name: Cluster compliance tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Run cluster set up script
        run: sh tools/chart-setup-test.sh ${{ secrets.API_KEY }}

      - name: Install Kubeaudit
        run: wget https://github.com/Shopify/kubeaudit/releases/download/v0.21.0/kubeaudit_0.21.0_linux_amd64.tar.gz
      
      - name: Run Kubeaudit
        run: ./kubeaudit all
