name: Trivy configuration scan
on:
  push:
    branches:
      - main
jobs:
  scan:
    name: Configuration scan
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          hide-progress: false
          exit-code: '1'
          ignore-unfixed: true
